# Generated by Django 5.0.4 on 2024-04-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company that is presenting the opportunity', max_length=100)),
                ('job_title', models.CharField(help_text='Job title', max_length=100)),
                ('job_url', models.URLField(help_text='The url for the job ad', null=True)),
                ('recruiter', models.CharField(help_text='Recruiter name', max_length=100, null=True)),
                ('recruiter_contacts', models.TextField(help_text='Recruiter contacts', null=True)),
                ('job_description', models.TextField(help_text='The job description')),
                ('date_applied', models.DateField(auto_now_add=True, help_text='The date I applied')),
                ('notes', models.TextField(help_text='Any notes relevant to the process')),
                ('rejected', models.BooleanField(default=False, help_text='If I was rejected in this process')),
            ],
        ),
    ]
