# Generated by Django 5.0.4 on 2024-04-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rka_jam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(help_text='Any notes relevant to the process', null=True),
        ),
    ]
