# Generated by Django 5.0.4 on 2024-04-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rka_jam_app', '0002_alter_jobapplication_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Any notes relevant to the process', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='recruiter_contacts',
            field=models.TextField(blank=True, help_text='Recruiter contacts', null=True),
        ),
    ]
