# Generated by Django 5.0.4 on 2024-04-23 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rka_jam_app', '0004_jobapplication_ghosted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date I applied'),
        ),
    ]
