# Generated by Django 5.0.4 on 2024-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rka_jam_app', '0005_alter_jobapplication_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, help_text='The url for the job ad', null=True),
        ),
    ]
