# Generated by Django 5.0.4 on 2024-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rka_jam_app', '0006_alter_jobapplication_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='not_proceeding',
            field=models.BooleanField(default=False, help_text="If I didn't want to proceed in the process"),
        ),
    ]
